CREATE TABLE `COM_INFORMATION` (
	`COM_INFORMATION_PK`	VARCHAR(30)	NOT NULL,
	`회사이름`	VARCHAR(30)	NULL
);

CREATE TABLE `CAR_NAME` (
	`CAR_NAME_PK`	VARCHAR(30)	NOT NULL,
	`자동차이름`	VARCHAR(30)	NULL
);

CREATE TABLE `YEAR` (
	`YEAR_PK`	VARCHAR(30)	NOT NULL,
	`연식`	VARCHAR(30)	NULL
);

CREATE TABLE `CAR_INFOR_NAME_YEAR` (
	`CAR_INFOR_YEAR_PK`	VARCHAR(30)	NOT NULL,
	`COM_INFORMATION_FK`	VARCHAR(30)	NOT NULL,
	`CAR_NAME_FK`	VARCHAR(30)	NOT NULL,
	`YEAR_FK`	VARCHAR(30)	NOT NULL,
	`자동차이름`	VARCHAR(30)	NULL
);

CREATE TABLE `OPTIONS` (
	`OPTIONS_PK`	VARCHAR(30)	NOT NULL,
	`옵션`	VARCHAR(200)	NULL
);

CREATE TABLE `CAR_OPT` (
	`CAR_OPT_PK`	VARCHAR(30)	NOT NULL,
	`CAR_NAME_FK`	VARCHAR(30)	NOT NULL,
	`OPTIONS_FK`	VARCHAR(30)	NOT NULL,
	`자동차이름`	VARCHAR(30)	NULL
);

ALTER TABLE `COM_INFORMATION` ADD CONSTRAINT `PK_COM_INFORMATION` PRIMARY KEY (
	`COM_INFORMATION_PK`
);

ALTER TABLE `CAR_NAME` ADD CONSTRAINT `PK_CAR_NAME` PRIMARY KEY (
	`CAR_NAME_PK`
);

ALTER TABLE `YEAR` ADD CONSTRAINT `PK_YEAR` PRIMARY KEY (
	`YEAR_PK`
);

ALTER TABLE `CAR_INFOR_NAME_YEAR` ADD CONSTRAINT `PK_CAR_INFOR_NAME_YEAR` PRIMARY KEY (
	`CAR_INFOR_YEAR_PK`,
	`COM_INFORMATION_FK`,
	`CAR_NAME_FK`,
	`YEAR_FK`
);

ALTER TABLE `OPTIONS` ADD CONSTRAINT `PK_OPTIONS` PRIMARY KEY (
	`OPTIONS_PK`
);

ALTER TABLE `CAR_OPT` ADD CONSTRAINT `PK_CAR_OPT` PRIMARY KEY (
	`CAR_OPT_PK`,
	`CAR_NAME_FK`,
	`OPTIONS_FK`
);

ALTER TABLE `CAR_INFOR_NAME_YEAR` ADD CONSTRAINT `FK_COM_INFORMATION_TO_CAR_INFOR_NAME_YEAR_1` FOREIGN KEY (
	`COM_INFORMATION_FK`
)
REFERENCES `COM_INFORMATION` (
	`COM_INFORMATION_PK`
);

ALTER TABLE `CAR_INFOR_NAME_YEAR` ADD CONSTRAINT `FK_CAR_NAME_TO_CAR_INFOR_NAME_YEAR_1` FOREIGN KEY (
	`CAR_NAME_FK`
)
REFERENCES `CAR_NAME` (
	`CAR_NAME_PK`
);

ALTER TABLE `CAR_INFOR_NAME_YEAR` ADD CONSTRAINT `FK_YEAR_TO_CAR_INFOR_NAME_YEAR_1` FOREIGN KEY (
	`YEAR_FK`
)
REFERENCES `YEAR` (
	`YEAR_PK`
);

ALTER TABLE `CAR_OPT` ADD CONSTRAINT `FK_CAR_NAME_TO_CAR_OPT_1` FOREIGN KEY (
	`CAR_NAME_FK`
)
REFERENCES `CAR_NAME` (
	`CAR_NAME_PK`
);

ALTER TABLE `CAR_OPT` ADD CONSTRAINT `FK_OPTIONS_TO_CAR_OPT_1` FOREIGN KEY (
	`OPTIONS_FK`
)
REFERENCES `OPTIONS` (
	`OPTIONS_PK`
);

